### ISSUE TITLE
Result page sorting appears to be on start time, rather than completion time

### ISSUE THREAD

**Issue by anarazel** [PGBuildFarm/server-code#12]
Hi,

often when one reloads the buildfarm page to see whether an animal finished, the top results stay the same, but newer results sneak in below. Afaict that's because the sorting is not based on when the results come in, but when the animals started. That makes it way harder to spot newer results, which doesn't seem great on the front page...

Andres

**Comment by adunstan** [comment]
Should be doable, just a matter of tuits. We keep the report timestamp in the build_status table but not in the dashboard table or the view it's based on. Changing that would be simple and then we would just need to change the query's order by.
