### ISSUE TITLE
Add total time of a test run to output

### ISSUE THREAD

**Issue by anarazel** [PGBuildFarm/server-code#9]
Hi,

Given the number of steps a test run has these days adding up the individual steps isn't really feasible anymore. It'd be useful if both show_log.pl and show_history.pl could show the total time of successful runs.

That'd make it much easier to pinpoint when we made regression tests much slower.

Regards,

Andres

**Comment by adunstan** [comment]
show_log.pl already has the total run time.

I will look at adding it to show_history, but I want to make sure it doesn't slow the history page down.
